# Common
server.port=${APP.SERVER.PORT}
spring.application.name=exam_7_zhanel_toishybekova


# Connection to MongoDB
spring.data.mongodb.host=${APP.MONGO.HOST}
spring.data.mongodb.port=${APP.MONGO.PORT}
spring.data.mongodb.database=${APP.MONGO.DB}

# Security
application.admin.password=${APP.ADMIN.PASSWORD}
application.jwt.signature.secret=${APP.JWT.SIGNATURE.SECRET}